# Final Locked Schema - Do not modify column names or order
# This is the single source of truth for all exports
COLUMN_ORDER = [
    # Race / Dog core
    "Track",
    "Race_Date",
    "Race_No",
    "Box",
    "Dog_Name",
    "Tab_No",
    # Group A – Identification
    "FF_Form",
    "BP",
    "A/S",
    "WT (kg)",
    "Trainer",
    "Sire",
    "Dam",
    "Owner",
    # Group B – Career / Aggregated stats
    "Career_W-P-S",
    "Prize_Money",
    "RTC",
    "DLR",
    "DLW",
    "Car_PM/s (G1)",
    "12m_PM/s (G2)",
    "API (G3)",
    "RTC/km",
    "Trainer_Win_%",
    "Trainer_Place_%",
    "Raced_Dist_W-P-S",
    "Crs_W-P-S",
    "Dist_W-P-S",
    "FU_W-P-S",
    "2U_W-P-S",
    "DOD",
    "Avg_Speed_km/h",
    "Min_Speed_km/h",
    "Max_Speed_km/h",
    # Group C – Historical race detail
    "Hist_Date",
    "Hist_Track",
    "Hist_Distance",
    "Hist_Finish_Pos",
    "Hist_Margin_L",
    "Hist_Race_Time",
    "Hist_Sec_Time",
    "Hist_Sec_Time_Adj",
    "Hist_Speed_km/h",
    "Hist_SOT",
    "Hist_RST",
    "Hist_BP",
    "Hist_Odds",
    "Hist_API",
    "Hist_Prize_Won",
    "Hist_Winner",
    "Hist_2nd_Place",
    "Hist_3rd_Place",
    "Hist_Settled_Turn",
    "Hist_Ongoing_Winners",
    "Hist_Track_Direction",
    # Metadata / aggregation
    "Hist_Count",
    "Data_Source_File",
    "Parse_Timestamp",
    # MEETING CONTEXT
    "Meeting_Type",
    "Weather",
    "Track_Condition",
    "Rail_Position",
    "Start_Type",
    "Prize_Pool",
    "Field_Size",
    "Race_Class",
    "Race_Grade",
    "Stewards_Report",
    # EXTENDED DOG INFO
    "DOB",
    "Age_Months",
    "Color_Detail",
    "Microchip_ID",
    "Registration_Status",
    "Breeding_State",
    "Sale_Price",
    "Kennel_Name",
    "Previous_Trainer",
    "Transfer_Date",
    "Last_Trial_Date",
    "Last_Trial_Time",
    "Injury_History",
    "Vaccination_Status",
    "Retirement_Status",
]
